apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mangalodon
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/Peerapon966/gitops
        revision: HEAD
        files:
          - path: apps/mangalodon/*/values.yaml
  template:
    metadata:
      name: mangalodon-{{ .path.basename }}
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Peerapon966/gitops
          targetRevision: HEAD
          path: apps/mangalodon/{{ .path.basename }}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: mangalodon-{{ .path.basename }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          enabled: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
